import {
  Fragment as MoodBox,
  StrictMode as NoSusMode,
  Profiler as LevelUp,
  Suspense as ChillMode,
  Children as Fam,
  PureComponent as SolidComp,
  cloneElement as copyPaste,
  createContext as vibinLowkey,
  createElement,
  createRef as tapInCheck,
  forwardRef as forwardRizz,
  isValidElement as noCapSigma,
  lazy as chill,
  memo as memoryFlex,
  useCallback as callbackRealQuick,
  useContext as famZone,
  useDebugValue,
  useEffect as vibeCheck,
  useState as moodRing,
  useReducer as moodManager,
  useMemo as slayyyy,
  useImperativeHandle,
  useLayoutEffect as glowUpCheck,
  useRef as tapIn,
  version as rizzVersion,
} from "react";

export {
  MoodBox,
  NoSusMode,
  LevelUp,
  ChillMode,
  Fam,
  SolidComp,
  copyPaste,
  vibinLowkey,
  createElement,
  tapInCheck,
  forwardRizz,
  noCapSigma,
  chill,
  memoryFlex,
  callbackRealQuick,
  famZone,
  useDebugValue,
  vibeCheck,
  moodRing,
  moodManager,
  slayyyy,
  useImperativeHandle,
  glowUpCheck,
  tapIn,
  rizzVersion,
};

export const Sigma = {
  MoodBox,
  NoSusMode,
  LevelUp,
  ChillMode,
  Fam,
  SolidComp,
  copyPaste,
  vibinLowkey,
  createElement,
  tapInCheck,
  forwardRizz,
  noCapSigma,
  chill,
  memoryFlex,
  callbackRealQuick,
  famZone,
  useDebugValue,
  vibeCheck,
  moodRing,
  moodManager,
  slayyyy,
  useImperativeHandle,
  glowUpCheck,
  tapIn,
  rizzVersion,
}

export default Sigma